### ISSUE TITLE
how to run the game?

### ISSUE THREAD

**Issue by fucusy** [wolfgangjiang/tetris-lua#1]
nice code! but how to run the game? what's the command line to start the software?

**Comment by wolfgangjiang** [comment]
This is a game made with Love2D framework, whose wiki is at https://love2d.org/wiki/Getting_Started.
On Linux platform, first install love2d framework, and then run "$ love /path/to/game/" to play.

Nowadays love2d also has a better distribution methodology. We are planning to add distribution downloads for this little exercise project, when we find time to do it.
